### ISSUE TITLE
Tags change for all displays

### ISSUE THREAD

**Issue by dpetzold** [lmanul/awesome-workspace-grid#1]
Hello,

Thank you very much for this. It is just what I was looking for. However when I switch tags on one display the tags on the other switch too. I'm not sure if that is on purpose or not.

Thank you,
  Derrick

**Comment by lmanul** [comment]
Hi Derrick,

Sorry for the delay! And thank you for the feedback. Yes, that is on purpose but I should probably make an option to control that behavior. I'll keep you posted.

**Comment by lmanul** [comment]
All right, I added an option `switch_all_screens` with this commit:

    https://github.com/lmanul/awesome-workspace-grid/commit/b4fb8f3785b9114dc128b0a6f8d286ab0ee5247a

I currently only have a laptop with me but as soon as I'm back with another monitor I will test it out properly -- I do think it should work though :-) Let me know if that addresses your issue!
